Repository TreinaDev/condominions, pull requests merged in 2024-07, with the labels that each got.

#40 Cadastrar Área comum
  app/controllers/common_areas_controller.rb
  app/models/common_area.rb
  app/models/condo.rb
  app/views/common_areas/edit.html.erb
  app/views/common_areas/new.html.erb
  app/views/common_areas/show.html.erb
  app/views/managers/new.html.erb
  config/locales/models/common_area.pt-BR.yml
  config/locales/models/manager.pt-BR.yml
  config/routes.rb
  db/migrate/20240628150121_rename_condominium_to_condo.rb
  db/schema.rb
  spec/factories/common_areas.rb
  spec/models/common_area_spec.rb
  spec/models/manager_spec.rb
  spec/requests/common_area_request_spec.rb
  spec/requests/manager_request_spec.rb
  spec/system/common_area/manager_edits_common_area_spec.rb
  spec/system/common_area/manager_registers_new_common_area_spec.rb
  spec/system/unit_types/user_manage_unit_types_spec.rb
Labels: enhancement

#42 Construir menu navegação
  app/assets/images/blank-profile-icon.webp
  app/assets/stylesheets/_custom_spacers.scss
  app/assets/stylesheets/application.bootstrap.scss
  app/controllers/home_controller.rb
  app/views/home/index.html.erb
  app/views/home/signup.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  spec/system/authentication/manager_register_new_manager_spec.rb
  spec/system/authentication/manager_sign_in_spec.rb
  spec/system/common_area/manager_registers_new_common_area_spec.rb
  spec/system/condos/manager_register_condo_spec.rb
  spec/system/tower/administrator_registers_condo_tower_spec.rb
  spec/system/unit_types/user_manage_unit_types_spec.rb
Labels: enhancement

#41 Cadastrar unidades
  .gitignore
  app/controllers/floors_controller.rb
  app/controllers/towers_controller.rb
  app/controllers/units_controller.rb
  app/models/floor.rb
  app/models/tower.rb
  app/models/unit.rb
  app/models/unit_type.rb
  app/views/floors/show.html.erb
  app/views/towers/edit_floor_units.html.erb
  app/views/towers/new.html.erb
  app/views/towers/show.html.erb
  app/views/units/show.html.erb
  config/locales/models/floor.pt-BR.yml
  config/locales/models/unit.pt-BR.yml
  config/routes.rb
  spec/factories/towers.rb
  spec/factories/units.rb
  spec/models/floor_spec.rb
  spec/models/tower_spec.rb
  spec/models/unit_spec.rb
  spec/system/floors/administrator_sees_floor_details_spec.rb
  spec/system/towers/administrator_registers_condo_tower_spec.rb
  spec/system/towers/administrator_sees_condo_tower_details_spec.rb
  spec/system/towers/adminstrator_register_floor_type_spec.rb
  spec/system/units/administrator_sees_unit_details_spec.rb
Labels: enhancement

#55 Cria o readme
  README.md
Labels: documentation

#59 Refatorar Torres
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/floors_controller.rb
  app/controllers/towers_controller.rb
  app/controllers/units_controller.rb
  app/helpers/application_helper.rb
  app/models/tower.rb
  app/views/layouts/application.html.erb
  app/views/towers/edit_floor_units.html.erb
  app/views/towers/new.html.erb
  db/migrate/20240703135555_add_status_to_tower.rb
  db/schema.rb
  spec/requests/tower_spec.rb
  spec/system/floors/administrator_sees_floor_details_spec.rb
  spec/system/towers/administrator_register_floor_type_spec.rb
  spec/system/towers/administrator_registers_condo_tower_spec.rb
  spec/system/towers/administrator_sees_condo_tower_details_spec.rb
  spec/system/towers/adminstrator_register_floor_type_spec.rb
  spec/system/units/administrator_sees_unit_details_spec.rb
Labels: bug, enhancement

#60 Refatoração de tipo de unidade
  app/controllers/condos_controller.rb
  app/controllers/unit_types_controller.rb
  app/models/condo.rb
  app/models/unit_type.rb
  app/views/shared/_navbar.html.erb
  app/views/unit_types/_form.html.erb
  app/views/unit_types/show.html.erb
  app/views/units/show.html.erb
  config/locales/condo.pt-BR.yml
  config/locales/models/address.pt-br.yml
  config/locales/models/condo.pt-BR.yml
  config/locales/models/unit_type.pt-BR.yml
  config/routes.rb
  db/migrate/20240702201411_add_fraction_to_unit_type.rb
  db/migrate/20240703193313_add_condo_id_to_unit_types.rb
  db/migrate/20240703200141_change_fraction_to_decimal.rb
  db/schema.rb
  spec/factories/unit_types.rb
  spec/models/unit_type_spec.rb
  spec/requests/unit_type_management_spec.rb
  spec/system/condos/manager_edit_condo_spec.rb
  spec/system/condos/manager_register_condo_spec.rb
  spec/system/towers/administrator_registers_condo_tower_spec.rb
  spec/system/unit_types/user_manage_unit_types_spec.rb
Labels: bug, enhancement

#63 API - Listar Condomínios
  README.md
  app/controllers/api/v1/api_controller.rb
  app/controllers/api/v1/condos_controller.rb
  app/models/condo.rb
  config/routes.rb
  spec/requests/apis/condo_spec.rb
Labels: enhancement, pague aluguel

#66 Adicionar área comum à barra de navegação
  app/views/shared/_navbar.html.erb
  app/views/unit_types/edit.html.erb
  spec/system/common_area/manager_registers_new_common_area_spec.rb
Labels: enhancement

#57 Inicia implementação do breadcrumb.
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/stylesheets/breadcrumb_style.css
  app/controllers/application_controller.rb
  app/controllers/common_areas_controller.rb
  app/controllers/condos_controller.rb
  app/controllers/floors_controller.rb
  app/controllers/managers_controller.rb
  app/controllers/towers_controller.rb
  app/controllers/unit_types_controller.rb
  app/controllers/units_controller.rb
  app/views/common_areas/index.html.erb
  app/views/condos/index.html.erb
  app/views/condos/new.html.erb
  app/views/condos/show.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_breadcrumb.html.erb
  app/views/towers/index.html.erb
  app/views/unit_types/index.html.erb
  config/locales/breadcrumb.pt-BR.yml
  config/routes.rb
  package.json
  spec/system/floors/administrator_sees_floor_details_spec.rb
  spec/system/towers/administrator_registers_condo_tower_spec.rb
  spec/system/towers/administrator_sees_condo_tower_details_spec.rb
  spec/system/unit_types/user_manage_unit_types_spec.rb
  spec/system/user_sees_breadcrumb_spec.rb
  yarn.lock
Labels: enhancement

#68 API - Detalhar condomínio
  README.md
  app/controllers/api/v1/condos_controller.rb
  config/routes.rb
  spec/requests/apis/condo_spec.rb
Labels: documentation, enhancement

#69 Listagem de torres
  app/controllers/towers_controller.rb
  app/views/condos/show.html.erb
  app/views/towers/index.html.erb
  spec/system/towers/administrator_view_condo_towers_spec.rb
Labels: enhancement

#70 API - Listar tipos de unidade
  README.md
  app/controllers/api/v1/api_controller.rb
  app/controllers/api/v1/unit_types_controller.rb
  app/models/unit_type.rb
  config/routes.rb
  spec/models/unit_type_spec.rb
  spec/requests/apis/unit_type_spec.rb
Labels: documentation, enhancement, pague aluguel

#71 Api-Validação do CPF do proprietário
  README.md
  app/controllers/api/v1/residents_controller.rb
  config/routes.rb
  spec/requests/apis/resident_spec.rb
Labels: documentation, enhancement, pague aluguel

#72 Implementa listagem de condomínios
  app/controllers/common_areas_controller.rb
  app/controllers/condos_controller.rb
  app/controllers/floors_controller.rb
  app/controllers/home_controller.rb
  app/controllers/residents_controller.rb
  app/controllers/towers_controller.rb
  app/controllers/unit_types_controller.rb
  app/controllers/units_controller.rb
  app/views/condos/index.html.erb
  app/views/home/index.html.erb
  config/locales/breadcrumb.pt-BR.yml
  config/routes.rb
  spec/system/user_sees_breadcrumb_spec.rb
  spec/system/user_sees_homepage_spec.rb
Labels: enhancement

#73 Confirmar cadastro morador
  .gitignore
  app/controllers/application_controller.rb
  app/controllers/residents_controller.rb
  app/models/application_record.rb
  app/models/condo.rb
  app/models/manager.rb
  app/models/resident.rb
  app/models/unit.rb
  app/views/home/signup.html.erb
  app/views/residents/confirm.html.erb
  app/views/residents/edit_photo.html.erb
  app/views/residents/sessions/new.html.erb
  app/views/shared/_navbar.html.erb
  config/environments/development.rb
  config/locales/models/resident.pt-BR.yml
  config/routes.rb
  spec/factories/residents.rb
  spec/mailers/resident_mailer_spec.rb
  spec/requests/resident_confirms_data_spec.rb
  spec/requests/resident_edits_photo_spec.rb
  spec/support/images/resident_photo.jpg
  spec/system/authentication/resident_sign_in_spec.rb
  spec/system/resident/resident_confirms_data_spec.rb
  spec/system/resident/resident_edits_photo_spec.rb
Labels: enhancement

#81 Refatoração da criação de andares e unidades
  app/controllers/towers_controller.rb
  app/models/tower.rb
  spec/mailers/resident_mailer_spec.rb
  spec/models/floor_spec.rb
  spec/models/tower_spec.rb
  spec/models/unit_spec.rb
  spec/requests/apis/unit_type_spec.rb
  spec/requests/tower_spec.rb
  spec/system/floors/administrator_sees_floor_details_spec.rb
  spec/system/resident/manager_register_new_resident_spec.rb
  spec/system/resident/resident_confirms_data_spec.rb
  spec/system/towers/administrator_register_floor_type_spec.rb
  spec/system/towers/administrator_sees_condo_tower_details_spec.rb
  spec/system/towers/administrator_view_condo_towers_spec.rb
  spec/system/units/administrator_sees_unit_details_spec.rb
  spec/system/user_sees_breadcrumb_spec.rb
Labels: enhancement

#83 Adiciona Endpoint de listagem de áreas comuns
  README.md
  app/controllers/api/v1/common_areas_controller.rb
  config/routes.rb
  spec/requests/apis/common_area_spec.rb
Labels: enhancement

#84 Multiplas propriedades residente
  README.md
  app/controllers/api/v1/residents_controller.rb
  app/controllers/application_controller.rb
  app/controllers/owners_controller.rb
  app/controllers/residents_controller.rb
  app/controllers/tenants_controller.rb
  app/models/resident.rb
  app/models/unit.rb
  app/views/owners/new.html.erb
  app/views/resident_mailer/notify_new_resident.html.erb
  app/views/residents/confirm.html.erb
  app/views/residents/new.html.erb
  app/views/tenants/new.html.erb
  config/locales/models/owner.pt-BR.yml
  config/locales/models/ownership.pt-BR.yml
  config/locales/models/resident.pt-BR.yml
  config/locales/models/tenant.pt-BR.yml
  config/routes.rb
  db/migrate/20240710182843_remove_resident_type_from_residents.rb
  db/migrate/20240710191437_remove_unit_from_residents.rb
  db/migrate/20240710200418_add_residence_to_residents.rb
  db/migrate/20240710220531_create_ownerships.rb
  db/migrate/20240710230858_add_unique_index_to_ownerships.rb
  db/migrate/20240712184732_add_tenant_and_owner_to_units.rb
  db/migrate/20240712191112_drop_ownerships.rb
  db/migrate/20240712191202_remove_residence_from_resident.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/residents.rb
  spec/mailers/resident_mailer_spec.rb
  spec/models/resident_spec.rb
  spec/requests/apis/resident_spec.rb
  spec/requests/manager_set_owner_spec.rb
  spec/requests/manager_set_tenants_spec.rb
  spec/requests/resident_confirms_data_spec.rb
  spec/requests/tower_spec.rb
  spec/system/authentication/resident_sign_in_spec.rb
  spec/system/resident/manager_register_new_resident_spec.rb
  spec/system/resident/manager_sets_resident_as_owner_spec.rb
  spec/system/resident/manager_sets_resident_as_tenant_spec.rb
  spec/system/resident/resident_confirms_data_spec.rb
  spec/system/resident/resident_edits_photo_spec.rb
Labels: enhancement

#96 Api buscar morador
  Gemfile.lock
  README.md
  app/controllers/api/v1/residents_controller.rb
  config/routes.rb
  spec/requests/apis/resident_spec.rb
  spec/system/resident/manager_sets_resident_as_owner_spec.rb
Labels: documentation, enhancement, pague aluguel

#98 Api buscar proprietario
  README.md
  app/controllers/api/v1/residents_controller.rb
  config/routes.rb
  spec/requests/apis/resident_spec.rb
Labels: documentation, enhancement, pague aluguel

#100 Popula o seed vastamente
  app/controllers/api/v1/residents_controller.rb
  db/seeds.rb
Labels: enhancement, pague aluguel

#105 Alinha necessidades dos seeds
  db/seeds.rb
Labels: bug, documentation, enhancement, pague aluguel

#99 Api detalhes unidade
  README.md
  app/controllers/api/v1/units_controller.rb
  app/models/unit.rb
  config/routes.rb
  spec/requests/apis/units_spec.rb
Labels: documentation, enhancement, pague aluguel

#102 Api listar unidades
  README.md
  app/controllers/api/v1/units_controller.rb
  app/models/condo.rb
  config/routes.rb
  spec/requests/apis/unit_spec.rb
Labels: documentation, enhancement, pague aluguel

#107 Atualiza Seeds
  db/seeds.rb
Labels: enhancement, pague aluguel

#97 Editar moradores
  app/controllers/condos_controller.rb
  app/controllers/owners_controller.rb
  app/controllers/residents_controller.rb
  app/controllers/tenants_controller.rb
  app/javascript/controllers/condo_controller.js
  app/javascript/controllers/index.js
  app/models/condo.rb
  app/views/condos/dashboard/_residents_list.html.erb
  app/views/condos/show.html.erb
  app/views/owners/new.html.erb
  app/views/residents/show.html.erb
  app/views/tenants/new.html.erb
  config/locales/breadcrumb.pt-BR.yml
  config/locales/models/resident.pt-BR.yml
  config/locales/models/tenant.pt-BR.yml
  config/routes.rb
  spec/models/condo_spec.rb
  spec/requests/form_request_residents.rb
  spec/requests/manager_sees_resident_details_spec.rb
  spec/requests/manager_set_owner_spec.rb
  spec/requests/manager_set_tenants_spec.rb
  spec/system/resident/manager_register_new_resident_spec.rb
  spec/system/resident/manager_sees_resident_details_spec.rb
  spec/system/resident/manager_sees_residents_list_spec.rb
  spec/system/resident/manager_sets_resident_as_owner_spec.rb
  spec/system/resident/manager_sets_resident_as_tenant_spec.rb
Labels: enhancement

#103 Reservar Área Comum
  Gemfile
  Gemfile.lock
  README.md
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/simple_calendar.scss
  app/controllers/reservations_controller.rb
  app/controllers/visitor_entries_controller.rb
  app/models/common_area.rb
  app/models/reservation.rb
  app/models/resident.rb
  app/views/common_areas/show.html.erb
  app/views/reservations/new.html.erb
  app/views/reservations/show.html.erb
  config/locales/breadcrumb.pt-BR.yml
  config/locales/models/reservation.pt-BR.yml
  config/routes.rb
  db/migrate/20240716143712_create_reservations.rb
  db/schema.rb
  spec/factories/reservations.rb
  spec/factories/residents.rb
  spec/models/reservation_spec.rb
  spec/requests/reservation_spec.rb
  spec/system/common_area/manager_edits_common_area_spec.rb
  spec/system/common_area/reservation/resident_cancel_common_area_reservation_spec.rb
  spec/system/common_area/reservation/resident_reserves_common_area_spec.rb
  spec/system/common_area/reservation/user_sees_reservation_details_spec.rb
  spec/system/resident/manager_sets_resident_as_tenant_spec.rb
Labels: enhancement

#117 Lista faturas index
  app/controllers/bills_controller.rb
  app/views/bills/index.html.erb
  app/views/condos/dashboard/_bills.html.erb
  config/locales/breadcrumb.pt-BR.yml
  config/locales/models/bills.pt-BR.yml
  config/routes.rb
  spec/system/fees/user_sees_fee_index_spec.rb
Labels: enhancement, pague aluguel

#109 Implementa mural de avisos
  app/assets/stylesheets/actiontext.css
  app/assets/stylesheets/application.bootstrap.scss
  app/controllers/announcements_controller.rb
  app/controllers/common_areas_controller.rb
  app/controllers/condos_controller.rb
  app/javascript/application.js
  app/models/announcement.rb
  app/models/condo.rb
  app/models/resident.rb
  app/views/active_storage/blobs/_blob.html.erb
  app/views/announcements/edit.html.erb
  app/views/announcements/index.html.erb
  app/views/announcements/new.html.erb
  app/views/announcements/show.html.erb
  app/views/condos/dashboard/_announcement_board.html.erb
  app/views/condos/show.html.erb
  app/views/layouts/action_text/contents/_content.html.erb
  config/locales/breadcrumb.pt-BR.yml
  config/locales/models/announcement.pt-BR.yml
  config/locales/pt-BR.yml
  config/routes.rb
  db/migrate/20240717185457_create_announcements.rb
  db/migrate/20240718011259_create_action_text_tables.action_text.rb
  db/migrate/20240718013114_remove_message_from_announcements.rb
  db/schema.rb
  db/seeds.rb
  package.json
  spec/factories/announcements.rb
  spec/models/announcement_spec.rb
  spec/requests/announcement_spec.rb
  spec/spec_helper.rb
  spec/support/capybara_helpers.rb
  spec/system/announcements/manager_deletes_announcements_spec.rb
  spec/system/announcements/manager_edits_announcements_spec.rb
  spec/system/announcements/manager_registers_new_announcement_spec.rb
  spec/system/announcements/user_sees_announcements_spec.rb
  yarn.lock
Labels: enhancement

#114 Consultar calendario de reserva de áreas comuns
  app/assets/stylesheets/simple_calendar.scss
  app/controllers/application_controller.rb
  app/controllers/common_areas_controller.rb
  app/controllers/home_controller.rb
  app/controllers/reservations_controller.rb
  app/models/reservation.rb
  app/views/common_areas/_reservation_calendar.html.erb
  app/views/common_areas/show.html.erb
  app/views/reservations/new.html.erb
  app/views/reservations/show.html.erb
  app/views/simple_calendar/_month_calendar.html.erb
  config/locales/models/common_area.pt-BR.yml
  config/locales/models/reservation.pt-BR.yml
  config/routes.rb
  spec/models/reservation_spec.rb
  spec/requests/common_area_spec.rb
  spec/requests/reservation_spec.rb
  spec/system/common_area/manager_edits_common_area_spec.rb
  spec/system/common_area/manager_registers_new_common_area_spec.rb
  spec/system/common_area/manager_sees_common_area_spec.rb
  spec/system/common_area/reservation/resident_cancel_common_area_reservation_spec.rb
  spec/system/common_area/reservation/resident_reserves_common_area_spec.rb
  spec/system/common_area/reservation/user_access_calendar_spec.rb
  spec/system/common_area/reservation/user_sees_reservation_details_spec.rb
  spec/system/common_area/user_access_common_area_spec.rb
Labels: enhancement

#127 Comprovante pagamento
  app/controllers/bills_controller.rb
  app/controllers/receipts_controller.rb
  app/models/bill.rb
  app/models/resident.rb
  app/views/bills/show.html.erb
  app/views/receipts/new.html.erb
  config/locales/breadcrumb.pt-BR.yml
  config/locales/models/receipt.pt-BR.yml
  config/locales/models/resident.pt-BR.yml
  config/routes.rb
  spec/requests/bills_spec.rb
  spec/support/images/cupom-fiscal.jpg
  spec/support/json/bill_2_details.json
  spec/support/response/response.txt
  spec/system/fees/user_send_receipt_spec.rb
Labels: documentation, enhancement, pague aluguel

#129 Testes de post
  spec/system/fees/user_send_receipt_spec.rb
Labels: bug, enhancement, pague aluguel

#108 Implementa Registro de Mandato de Sindico
  app/controllers/superintendents_controller.rb
  app/models/condo.rb
  app/models/resident.rb
  app/models/superintendent.rb
  app/views/condos/show.html.erb
  app/views/shared/_navbar.html.erb
  app/views/superintendents/_form.html.erb
  app/views/superintendents/edit.html.erb
  app/views/superintendents/new.html.erb
  app/views/superintendents/show.html.erb
  config/locales/breadcrumb.pt-BR.yml
  config/locales/models/superintendent.pt-BR.yml
  config/routes.rb
  db/migrate/20240717022634_create_superintendents.rb
  db/migrate/20240717033254_add_condo_to_superintendents.rb
  db/migrate/20240717033644_remove_resident_from_superintendents.rb
  db/migrate/20240717033755_add_tenant_to_superintendents.rb
  db/schema.rb
  spec/factories/superintendents.rb
  spec/models/superintendent_spec.rb
  spec/requests/manager_edit_superintendent_spec.rb
  spec/requests/manager_registers_superintendent_spec.rb
  spec/system/common_area/manager_view_list_of_common_areas_spec.rb
  spec/system/superintendent/manager_edit_superintendent_spec.rb
  spec/system/superintendent/manager_register_superintendent_spec.rb
  spec/system/superintendent/user_sees_superintendent_details_spec.rb
Labels: enhancement

#128 Consultar no Pague Aluguel a taxa de uso de área comum
  app/controllers/bills_controller.rb
  app/helpers/currency_helper.rb
  app/models/common_area.rb
  app/services/bill_service.rb
  app/views/common_areas/show.html.erb
  config/api.yml
  config/application.rb
  config/locales/messages.pt-BR.yml
  config/locales/models/bills.pt-BR.yml
  spec/models/common_area_spec.rb
  spec/support/json/common_areas/common_area_fee.json
  spec/support/json/common_areas/common_area_fee_error.json
  spec/support/json/common_areas/common_area_fees.json
  spec/system/common_area/user_sees_common_area_tax_spec.rb
  spec/system/fees/user_sees_fee_details_spec.rb
  spec/system/fees/user_sees_fee_index_spec.rb
  spec/system/fees/user_sees_fee_spec.rb
Labels: enhancement, pague aluguel

#130 Gerar cobrança avulsa de reserva de área comum no Pague Aluguel
  app/controllers/reservations_controller.rb
  app/models/common_area.rb
  app/models/reservation.rb
  app/views/common_areas/_reservation_calendar.html.erb
  spec/support/json/common_areas/single_charge.json
  spec/system/common_area/reservation/resident_reserves_common_area_spec.rb
  spec/system/common_area/user_sees_common_area_fee_spec.rb
Labels: enhancement, pague aluguel

#132 Refatora nome torres endpoints
  README.md
  app/controllers/api/v1/residents_controller.rb
  app/models/condo.rb
  app/models/unit.rb
  db/schema.rb
  spec/requests/apis/resident_spec.rb
  spec/requests/apis/unit_spec.rb
Labels: documentation, enhancement, pague aluguel

#137 Gera cancelamento de cobrança na aplicação PagueAluguel
  app/controllers/reservations_controller.rb
  app/models/reservation.rb
  db/migrate/20240722025316_add_single_charge_id_to_reservations.rb
  db/schema.rb
  spec/support/json/common_areas/single_charge_cancelation.json
  spec/system/common_area/reservation/resident_cancel_common_area_reservation_spec.rb
  spec/system/common_area/reservation/resident_reserves_common_area_spec.rb
Labels: enhancement, pague aluguel

#136 Corrige envio de convite para cadastro de morador
  app/controllers/residents/passwords_controller.rb
  app/controllers/tenants_controller.rb
  app/views/announcements/show.html.erb
  app/views/residents/confirm.html.erb
  app/views/residents/passwords/edit.html.erb
  app/views/shared/_navbar.html.erb
  config/locales/breadcrumb.pt-BR.yml
  config/locales/models/resident.pt-BR.yml
  config/routes.rb
  spec/system/resident/manager_sets_resident_as_tenant_spec.rb
Labels: bug, enhancement

#142 Atualiza informações do README.md
  README.md
Labels: documentation

#146 Limita quantidade de andares e unidades por andar que podem ser criadas em uma torre
  app/models/tower.rb
  spec/models/tower_spec.rb
Labels: bug, enhancement

#143 Adicionar rodapé
  README.md
  app/assets/stylesheets/style.scss
  app/views/layouts/application.html.erb
  app/views/owners/new.html.erb
  app/views/shared/_footer.html.erb
  app/views/shared/_navbar.html.erb
  app/views/tenants/new.html.erb
Labels: bug, documentation, enhancement

#131 Implementa Lançamento de Multas pelo Síndico
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/fines_controller.rb
  app/controllers/residents_controller.rb
  app/javascript/controllers/fines_controller.js
  app/javascript/controllers/index.js
  app/models/single_charge.rb
  app/models/unit.rb
  app/views/condos/show.html.erb
  app/views/fines/new.html.erb
  config/initializers/money.rb
  config/locales/breadcrumb.pt-BR.yml
  config/locales/models/single_charge.pt-BR.yml
  config/routes.rb
  db/migrate/20240718203804_create_single_charges.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/single_charges.rb
  spec/models/single_charge_spec.rb
  spec/requests/form_request_towers_spec.rb
  spec/requests/superintendent_register_fine_spec.rb
  spec/system/common_area/reservation/resident_cancel_common_area_reservation_spec.rb
  spec/system/common_area/reservation/resident_reserves_common_area_spec.rb
  spec/system/superintendent/superintendent_register_fine_spec.rb
Labels: enhancement, pague aluguel
